### ISSUE TITLE
Compliance test pass, but process won't exit

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-kad-routing#2]
```
> node tests/compliance-test.js

TAP version 13
# Simple findPeers test
ok 1 null
ok 2 null
ok 3 should be equal
# time: 113 ms
# should exit here successfully
```

**Comment by masylum** [comment]
The issue is that teardown is never called, therefore the swarms keep listening and node does not exist accordingly.

https://github.com/diasdavid/abstract-peer-routing/blob/master/tests/base-test.js#L11

Why is this line commented? Uncommenting solves the issue.

Related: https://github.com/diasdavid/node-libp2p-kad-routing/pull/4
